sudo: required
services: 
  - docker
before_install:
  - docker build -t lingta/react-test -f ./client/Dockerfile.dev ./client

script:
  - - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t lingta/multi-client ./client
  - docker build -t lingta/multi-nginx ./nginx
  - docker build -t lingta/multi-server ./server
  - docker build -t lingta/multi-worker ./worker
  